Secure_Bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls,name='admin'),
    path('create_account/', include('create_account.urls',namespace='create_account')),
    path('create_internal_account/', include('internal_account_creation.urls')),
    path('login/', include('login.urls',namespace='login')),
    path('user_home/', include('user_home.urls')),
    path('transaction/', include('transactions.urls')),
    path('internal_user/', include('internal_user.urls')),
    path('admin_app/', include('admin_app.urls'))
]

internal_user/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

app_name = "internal_user"

urlpatterns = [
    path('initFundDeposit', views.initFundDeposit, name='init-fund-deposit'),
    path('searchCustomer', views.searchCustomer, name='search-customer'),
    path('depositFund', views.depositFund, name='deposit-fund'),
    path('depositTemplate', views.depositTemplate, name='deposit-template'),
    path('initIssueCheque', views.initIssueCheque, name='init-issue-cheque'),
    path('issueChequeTemplate', views.issueChequeTemplate, name='init-issue-cheque'),
    path('issueCheque', views.issueCheque, name='issue-cheque'),
    path('initViewCustomer', views.initViewCustomer, name='init-view-customer'),
    path('viewCustomer', views.viewCustomer, name='view-customer'),
    path('createCustomer', views.createCustomer, name='create-customer'),
    path('initModifyCustomer', views.initModifyCustomer, name='init-modify-customer'),
    path('modifyCustomerTemplate', views.modifyCustomerTemplate, name='modify-customer-template'),
    path('modifyCustomer', views.modifyCustomer, name='modify-customer'),
    path('deleteCustomer', views.deleteCustomer, name='delete-customer'),
    path('viewRequests', views.viewRequests, name='view-requests'),
    path('', views.viewRequests, name='view-requests'),
    path('viewInternalRequests', views.viewInternalRequests, name='view-internal-requests'),
    path('viewUpdates', views.view_updates, name='view-updates'),
    path('viewOpenRequests',views.view_open_accs,name="view-open-accs"),
    path('viewCloseRequests',views.view_close_accs,name="view-close-accs"),
    path('updateRequest', views.updateRequest, name='update-request'),
    path('verifyCheque', views.verifyCheque, name='verify-cheque'),
    path('initVerifyCheque', views.initVerifyCheque, name='init-verify-cheque'),
    path('updateInternalRequest', views.updateInternalRequest, name='update-internal-request'),
    path('ApproveUpdate',views.approve_open_request,name='approve-open-request'),
    path('ApproveClose',views.approve_close_request,name='approve-close-request')
]

urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

app_name = "login"

urlpatterns = [
    path('', views.login_user, name='login_base'),
    path('block/', views.login_block, name='login_bolck'),
]

internal_user/models.py
from django.db import models

# Create your models here.

internal_user/forms.py
from django import forms
from django.core.validators import MinValueValidator

class FundDepositForm(forms.Form):
    customerName = forms.CharField(label='Name')
    customerId = forms.IntegerField(label='Customer Id', validators=[MinValueValidator(1)])
    accountId = forms.IntegerField(label='Account Id', validators=[MinValueValidator(1)])
    accountType = forms.CharField(label='Account type')
    depositAmount = forms.FloatField(label='Deposit amount', validators=[MinValueValidator(0.01)])

class IssueChequeForm(forms.Form):
    customerName = forms.CharField(label='Name')
    accountId = forms.IntegerField(label='Account Id', validators=[MinValueValidator(1)])
    accountType = forms.CharField(label='Account type')
    chequeAmount = forms.FloatField(label='Cheque amount', validators=[MinValueValidator(0.01)])
    recipientName = forms.CharField(label='Recipient name')

class CustomerForm(forms.Form):
    customerName = forms.CharField(label='Name')
    customerId = forms.IntegerField(label='Customer Id', validators=[MinValueValidator(1)])
    accountId = forms.IntegerField(label='Account Id', validators=[MinValueValidator(1)])
    accountType = forms.CharField(label='Account type')
    customerEmail = forms.EmailField(label='Email')
    customerPhoneNum = forms.IntegerField(label='Phone number', validators=[MinValueValidator(1)])

internal_user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

from .forms import FundDepositForm, IssueChequeForm, CustomerForm
from django.conf import settings
from internal_user.approvals import _viewRequests, _updateRequest, _view_updates, _approve_update, _view_open_accs,_approve_open_request,_view_close_accs,_approve_close_request,_viewInternalRequests,_updateInternalRequest
from internal_user.utils import render_to_pdf,verify_file

customers = [
    {
        'customerName': 'James Karen',
        'customerId': 1,
        'accountId': 1,
        'accountType': 'Savings'
    },
    {
        'customerName': 'Jane Doe',
        'customerId': 2,
        'accountId': 2,
        'accountType': 'Checking'
    }
]


def initFundDeposit(request):
    return render(request, 'init_fund_deposit.html')

def depositTemplate(request):
    form = FundDepositForm(initial={'customerName': request.POST['customerName'],
                                    'customerId': request.POST['customerId'],
                                    'accountId': request.POST['accountId'],
                                    'accountType': request.POST['accountType']
    })
    return render(request, 'depositFund.html', {'form':form})

def depositFund(request):
    if request.method == 'POST':
        form = FundDepositForm(request.POST)
        if form.is_valid():
            depositAmount = form.cleaned_data.get('depositAmount')
            ## backend code goes here
            messages.success(request, f'Amount deposited successfully {depositAmount}')
            return redirect('./initFundDeposit')

def initIssueCheque(request):
    context = {'context_page' : 'issue_cheque'}
    return render(request, 'init_issue_cheque.html', context)

def issueChequeTemplate(request):
    form = IssueChequeForm(initial={'customerName': request.POST['customerName'],
                                    'customerId': request.POST['customerId'],
                                    'accountId': request.POST['accountId'],
                                    'accountType': request.POST['accountType']
    })
    return render(request, 'issueCheque.html', {'form':form})

def issueCheque(request):
    if request.method == 'POST':
        form = IssueChequeForm(request.POST)
        if form.is_valid():
            chequeAmount = form.cleaned_data.get('chequeAmount')
            ## backend code goes here
            messages.success(request, f'Cheque Issued successfully {chequeAmount}')
            cheque_id = 222
            data = {
                'pay_to':form.cleaned_data.get('recipientName'),
                'cheque_id': cheque_id,
                'amount': form.cleaned_data.get('chequeAmount'),
            }
            pdf = render_to_pdf('pdf_template.html', data)
            if pdf:
                response = HttpResponse(pdf, content_type='application/pdf')
                filename = "Cheque_"+str(cheque_id)+".pdf"
                content = "attachment; filename=%s" % (filename)
                response['Content-Disposition'] = content
                return response

def verifyCheque(request):
    try:
        try:
            chequeId = request.FILES['cheque'].name.split('_')[-1].replace(settings.SIGNATURE_FILES_FORMAT,'')
        except:
            return HttpResponse("Invalid file name format, file name should be of form Cheque_CHEQUEID.pdf")
        status = verify_file('public.pem', request.FILES['cheque'], settings.SIGNATURE_FILES + str(chequeId) + settings.SIGNATURE_FILES_FORMAT)
        status = not status
        context = {'tampared': status}
    except:
        return HttpResponse("Error occured while verifying cheque")
    return render(request, 'verify_cheque.html', context)

def initVerifyCheque(request):
    return render(request, 'init_verify.html')


def searchCustomer(request):
    context = {
        'customers' : customers,
        'customerSearchString' : request.POST['customerSearchString']
    }
    if request.POST['context_page']=='deposit':
        return render(request, 'init_fund_deposit.html', context)
    elif request.POST['context_page']=='issue_cheque':
        return render(request, 'init_issue_cheque.html', context)
    elif request.POST['context_page']=='view_customer':
        return render(request, 'init_view_customer.html', context)
    elif request.POST['context_page']=='modify_customer':
        return render(request, 'init_modify_customer.html', context)
    elif request.POST['context_page']=='delete_customer':
        return render(request, 'delete_customer_account.html', context)

def initViewCustomer(request):
    context = {'context_page' : 'view_customer'}
    return render(request, 'init_view_customer.html', context)

def viewCustomer(request):
    if request.method == 'POST':
        form = CustomerForm(initial={'customerName': request.POST['customerName'],
                                    'customerId': request.POST['customerId'],
                                    'accountId': request.POST['accountId'],
                                    'accountType': request.POST['accountType']
        })
        ##Get all customer realted data from database and populate form
        return render(request, 'view_customer.html', {'form':form})

def createCustomer(request):
    return redirect(settings.BASE_URL+'/create_account')

def initModifyCustomer(request):
    context = {'context_page' : 'modify_customer'}
    return render(request, 'init_modify_customer.html', context)

def modifyCustomerTemplate(request):
    if request.method == 'POST':
        # populate all customer related data here in the form
        form = CustomerForm(initial={'customerName': request.POST['customerName'],
                                    'customerId': request.POST['customerId'],
                                    'accountId': request.POST['accountId'],
                                    'accountType': request.POST['accountType']
        })
        return render(request, 'modify_customer_template.html',{'form':form})

def modifyCustomer(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        #backend code goes here, save modified form data to db
        return redirect('./initModifyCustomer')

def deleteCustomer(request):
    context = {'context_page' : 'delete_customer'}
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            ## backend code goes here. Code to delete/close customer account
            messages.success(request, f'Customer account deleted successfully')
            return redirect(settings.BASE_URL+'/user_home/home')
        else:
            messages.error(request, f'Failed to delete customer account')
            return redirect(settings.BASE_URL+'/user_home/home')
    else:
        form = CustomerForm()
        return render(request, 'delete_customer_account.html', context)

def viewRequests(request):
    return _viewRequests(request)

def updateRequest(request):
    return _updateRequest(request)

def viewInternalRequests(request):
    return _viewInternalRequests(request)

def view_updates(request):
    return _view_updates(request)

def view_open_accs(request):
    return _view_open_accs(request)

def view_close_accs(request):
    return _view_close_accs(request)

def updateInternalRequest(request):
    return _updateInternalRequest(request)

def approve_update(request):
    return _approve_update(request)

def approve_open_request(request):
    return _approve_open_request(request)

def approve_close_request(request):
    return _approve_close_request(request)

internal_user/templates/base_customer_search.html
<div>
    <div class="form-group">
        <form action='./searchCustomer' method="post">
            <label>Search Customer:</label>
            {% csrf_token %}
            <input type="text" id="customerSearchString" class="form-control" name="customerSearchString" value={{customerSearchString}}><br>
            <input type="hidden" name="context_page" value="{{context_page}}">
            <input type="submit" value="Search" class="btn btn-primary float-right app-submit"><br><br>
        </form>
    </div>

    <div>
        <table class="table table-hover">
            <thead class="thead-dark">
               <tr>
                  <th>Customer Name</th>
                  <th>Customer ID</th>
                  <th>Account ID</th>
                  <th>Account Type</th>
              </tr>
            </thead>
          {% for customer in customers %}
                <tr>
                    <td name="customerName">{{customer.customerName}}</td>
                    <td name="customerId">{{customer.customerId}}</td>
                    <td name="accountId">${{customer.accountId}}</td>
                    <td name="accountType">{{customer.accountType}}</td>
                    <td>
                        <form method="POST" action="{{action_path}}">
                            {% csrf_token %}
                            <input type="hidden" name="customerName" value="{{customer.customerName}}">
                            <input type="hidden" name="customerId" value="{{customer.customerId}}">
                            <input type="hidden" name="accountId" value="{{customer.accountId}}">
                            <input type="hidden" name="accountType" value="{{customer.accountType}}">
                            <input type="submit" value="{{button_value}}" />
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

internal_user/templates/create_customer_account.html
{% extends "tier2_homepage.html" %}
{% load crispy_forms_tags%}

{% block content %}
<div>
    <div>
        <h2>Create customer account</h2><br><br>
    </div>
    <div class="form-group">
        <form action='./createCustomer' method="post">
            {% csrf_token %}
            <input type="submit" id="create_cust" value="Click to create new customer account">
        </form>
    </div>
</div>
{% endblock content %}

internal_user/templates/delete_customer_account.html
{% extends "tier2_homepage.html" %}
{% load crispy_forms_tags%}

{% block content %}
<div>
    <div>
        <h2>Delete customer account</h2><br><br>
    </div>
{% include "base_customer_search.html" with action_path="./deleteCustomer" button_value="Delete customer" context_page="delete_customer" %}
</div>
{% endblock content %}

internal_user/templates/depositFund.html
{% extends "tier1_homepage.html" %}
{% load crispy_forms_tags%}
{% block javascript %}
 <script>
    $(function(){
         $('#id_depositAmount').keyup(function(e){
            var amount = $("#id_depositAmount")[0].value;
            if(amount == ""){
                $('#deposit').prop("disabled", true);
            }
            else{
                $('#deposit').prop("disabled", false);
            }
        });
    });
  </script>
{% endblock %}
{% block content %}
<div>
    <div>
        <h2>Initiate fund deposit</h2><br><br>
    </div>
    <div class="form-group">
    <form action='./depositFund' method="post">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" id="deposit" value="Deposit" disabled >
    </form>
</div>
</div>
{% endblock content %}

internal_user/templates/init_fund_deposit.html
{% extends "tier1_homepage.html" %}
{% block javascript %}
{% endblock %}
{% block content %}

<div>
    <div>
        <h2>Initiate fund deposit</h2><br><br>
    </div>
{% include "base_customer_search.html" with action_path="./depositTemplate" button_value="Select" context_page="deposit" %}
</div>
{% endblock content %}

internal_user/templates/init_issue_cheque.html
{% extends "tier1_homepage.html" %}
{% block javascript %}
{% endblock %}
{% block content %}

<div>
    <div>
        <h2>Issue cashier cheque</h2><br><br>
    </div>
{% include "base_customer_search.html" with action_path="./issueChequeTemplate" button_value="Select" context_page="issue_cheque"%}
</div>
{% endblock content %}

internal_user/templates/init_modify_customer.html
{% extends "tier2_homepage.html" %}
{% load crispy_forms_tags%}

{% block content %}
<div>
    <div>
        <h2>Modify customer account</h2><br><br>
    </div>
{% include "base_customer_search.html" with action_path="./modifyCustomerTemplate" button_value="Select" context_page="modify_customer" %}
</div>
{% endblock content %}

internal_user/templates/init_verify.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div>
    <div>
        <h2>Verify cheque</h2><br><br>
    </div>
    <div>
      <form method="post" enctype="multipart/form-data" action="./verifyCheque">
        {% csrf_token %}
        <input type="file" name="cheque">
        <button type="submit">Upload</button>
      </form>
    </div>
</div>
{% endblock content %}

internal_user/templates/init_view_customer.html
{% extends "tier1_homepage.html" %}

{% block content %}

<div>
    <div>
        <h2>View customer</h2><br><br>
    </div>
{% include "base_customer_search.html" with action_path="./viewCustomer" button_value="Select" context_page="view_customer" %}

</div>
{% endblock content %}

internal_user/templates/issueCheque.html
{% extends "tier1_homepage.html" %}
{% load crispy_forms_tags%}
{% block javascript %}
 <script>
    $(function(){
         $('#id_chequeAmount').keyup(function(e){
            var amount = $("#id_chequeAmount")[0].value;
            if(amount == ""){
                $('#issue_cheque').prop("disabled", true);
            }
            else{
                $('#issue_cheque').prop("disabled", false);
            }
        });
    });
  </script>
{% endblock %}
{% block content %}
<div>
    <div>
        <h2>Issue cashier cheque</h2><br><br>
    </div>
    <div class="form-group">
        <form action='./issueCheque' method="post">
            {% csrf_token %}
            {{form|crispy}}

            <input type="submit" id="issue_cheque" value="Issue Cheque" disabled >
        </form>
    </div>
</div>

{% endblock content %}

internal_user/templates/modify_customer_template.html
{% extends "tier2_homepage.html" %}
{% load crispy_forms_tags%}

{% block content %}
<div>
    <div>
        <h2>Modify customer account</h2><br><br>
    </div>
    <div class="form-group">
        <form class="read" action="./modifyCustomer">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" id="modify_customer" value="Modify customer" class="btn btn-primary app-submit">
        </form>

    </div>
</div>
{% endblock content %}

internal_user/templates/pdf_template.html
<!DOCTYPE HTML>
<html>
    <body>
    Cheque # {{cheque_id}}<br/>
    Pay to: {{pay_to}}<br/>
    Amount: {{amount}} <br/>
    Date: {% now "jS F Y H:i" %}
    </body>
</html>

internal_user/templates/verify_cheque.html
{% extends "base.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div>
    <div>
        <h2>Verify cheque</h2><br><br>
    </div>
    <div>
        <label>Cheque Tampered: </label>
        <p>{{tampared}}</p>
    </div>
</div>
{% endblock content %}

internal_user/templates/view_customer.html
{% extends "tier1_homepage.html" %}
{% load crispy_forms_tags%}
{% block content %}
<div>
    <div>
        <h2>View customer</h2><br><br>
    </div>
    <div class="form-group">
        <form class="read">
            {% csrf_token %}
            {{form|crispy}}
        </form>
    </div>
</div>
{% endblock content %}